name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all-features --verbose && cargo build --no-default-features --verbose
    - name: Run tests
      run: cargo test --no-default-features && cargo test --no-default-features --features rational && cargo test --no-default-features --features rational,quaternion,libm,bytemuck,serde && cargo test --all-features && cargo test && cargo test --features rational,quaternion,bytemuck,serde
